### ISSUE TITLE
I'm getting so many errors.

### ISSUE THREAD

**Issue by dheerajbred** [januwA/flutter_anime_app#1]
Hi,

I'm getting so many errors. Am I missing something?

![image](https://user-images.githubusercontent.com/46578244/61187347-facf4d00-a68d-11e9-9426-f6b4bb6440b1.png)

**Comment by januwA** [comment]
Try to execute `flutter packages pub run build_runner watch --delete-conflicting-outputs` in the project directory.

![image](https://user-images.githubusercontent.com/22570563/61192417-bcb24780-a6e6-11e9-8d79-745567ab7d89.png)
